export const BOOK_TYPES = {
  novel: 'novel',
  story: 'story',
  shortstory: 'shortstory',
  other: 'other',
  microstory: 'microstory',
  documental: 'documental',
  collection: 'collection',
  poem: 'poem',
  piece: 'piece',
  cycle: 'cycle',
  conditionalcycle: 'conditionalcycle',
  epic: 'epic',
  na: 'na',
};

export const BOOK_TYPE_NAMES = {
  [BOOK_TYPES.novel]: 'Роман',
  [BOOK_TYPES.story]: 'Повесть',
  [BOOK_TYPES.shortstory]: 'Рассказ',
  [BOOK_TYPES.other]: 'Прочее',
  [BOOK_TYPES.microstory]: 'Микрорассказ',
  [BOOK_TYPES.documental]: 'Документальное произведение',
  [BOOK_TYPES.collection]: 'Сборник',
  [BOOK_TYPES.poem]: 'Стихотворение',
  [BOOK_TYPES.piece]: 'Пьеса',
  [BOOK_TYPES.cycle]: 'Цикл',
  [BOOK_TYPES.conditionalcycle]: 'Условный цикл',
  [BOOK_TYPES.epic]: 'Роман-эпопея',
  [BOOK_TYPES.na]: 'Не определено',
};
